# Generated by Django 5.0.4 on 2024-05-17 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FAQ_name_uz', models.CharField(max_length=100)),
                ('FAQ_name_en', models.CharField(max_length=100)),
                ('answer_uz', models.TextField()),
                ('answer_en', models.TextField()),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQs',
                'db_table': 'FAQ',
            },
        ),
        migrations.CreateModel(
            name='Requirements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requirements_parts_uz', models.CharField(max_length=100)),
                ('requirements_parts_en', models.CharField(max_length=100)),
                ('requirements_title_uz', models.TextField()),
                ('requirements_title_en', models.TextField()),
                ('requirements_description_uz', models.TextField()),
                ('requirements_description_en', models.TextField()),
            ],
            options={
                'verbose_name': 'Requirement',
                'verbose_name_plural': 'Requirements',
                'db_table': 'Requirements',
            },
        ),
    ]
